export const OPEN_DETAILED_VIEW = Symbol("OPEN_DETAILED_VIEW");
export const CLOSE_DETAILED_VIEW = Symbol("CLOSE_DETAILED_VIEW");
export const LOADING_DETAILED_VIEW = Symbol("LOADING_DETAILED_VIEW");
export const LOADED_DETAILED_VIEW = Symbol("LOADED_DETAILED_VIEW");
export const FLIX_DATA_LOADED = Symbol("FLIX_DATA_LOADED");
export const FLIX_DATA_LOAD_FAILED = Symbol("FLIX_DATA_LOAD_FAILED");
export const CHANGE_COUNTRY = Symbol("CHANGE_COUNTRY");